version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/ats_db?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root@123
    depends_on:
      - db
    networks:
      - ats-network

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root@123
      - MYSQL_DATABASE=ats_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - ats-network

volumes:
  mysql-data:

networks:
  ats-network:
    driver: bridge 